name: Package Application with Pyinstaller

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
          spec: src/test.spec

      - uses: actions/upload-artifact@v2
        with:
          name: boundless-firmware-scheduler
          path: src/dist/windows
